export type Preset = {
  id: string;
  name: string;
  fonts: string;
  fontFamily: { display: string; body: string };
  colors: Record<string, string>;
  dark: boolean;
};

export const presets: Preset[] = [
  {
    id: "terminal-green",
    name: "Terminal Green",
    fonts: "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap",
    fontFamily: { display: "'JetBrains Mono', monospace", body: "'JetBrains Mono', monospace" },
    colors: {
      "--bg-primary": "#0d1117",
      "--bg-secondary": "#161b22",
      "--text-primary": "#e6edf3",
      "--text-secondary": "#8b949e",
      "--text-dim": "#484f58",
      "--accent": "#39d353",
      "--accent-glow": "rgba(57,211,83,0.3)",
      "--border": "#30363d",
    },
    dark: true,
  },
  {
    id: "creative-voltage",
    name: "Creative Voltage",
    fonts: "https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=Space+Mono:wght@400;700&display=swap",
    fontFamily: { display: "'Syne', sans-serif", body: "'Space Mono', monospace" },
    colors: {
      "--bg-primary": "#0066ff",
      "--bg-secondary": "#1a1a2e",
      "--text-primary": "#ffffff",
      "--text-secondary": "rgba(255,255,255,0.7)",
      "--text-dim": "rgba(255,255,255,0.4)",
      "--accent": "#d4ff00",
      "--accent-glow": "rgba(212,255,0,0.3)",
      "--border": "rgba(255,255,255,0.15)",
    },
    dark: true,
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    fonts: "https://api.fontshare.com/v2/css?f[]=clash-display@700&f[]=satoshi@400,500&display=swap",
    fontFamily: { display: "'Clash Display', sans-serif", body: "'Satoshi', sans-serif" },
    colors: {
      "--bg-primary": "#0a0f1c",
      "--bg-secondary": "#111827",
      "--text-primary": "#e8eaed",
      "--text-secondary": "rgba(232,234,237,0.5)",
      "--text-dim": "rgba(232,234,237,0.3)",
      "--accent": "#00ffcc",
      "--accent-glow": "rgba(0,255,204,0.3)",
      "--border": "rgba(0,255,204,0.15)",
    },
    dark: true,
  },
  {
    id: "bold-signal",
    name: "Bold Signal",
    fonts: "https://fonts.googleapis.com/css2?family=Archivo+Black&family=Space+Grotesk:wght@400;500&display=swap",
    fontFamily: { display: "'Archivo Black', sans-serif", body: "'Space Grotesk', sans-serif" },
    colors: {
      "--bg-primary": "#1a1a1a",
      "--bg-secondary": "#2d2d2d",
      "--text-primary": "#ffffff",
      "--text-secondary": "rgba(255,255,255,0.7)",
      "--text-dim": "rgba(255,255,255,0.4)",
      "--accent": "#FF5722",
      "--accent-glow": "rgba(255,87,34,0.3)",
      "--border": "#3a3a3a",
    },
    dark: true,
  },
  {
    id: "dark-botanical",
    name: "Dark Botanical",
    fonts: "https://fonts.googleapis.com/css2?family=Cormorant:wght@400;600&family=IBM+Plex+Sans:wght@300;400&display=swap",
    fontFamily: { display: "'Cormorant', serif", body: "'IBM Plex Sans', sans-serif" },
    colors: {
      "--bg-primary": "#0f0f0f",
      "--bg-secondary": "#1a1a1a",
      "--text-primary": "#e8e4df",
      "--text-secondary": "#9a9590",
      "--text-dim": "#6a6560",
      "--accent": "#d4a574",
      "--accent-glow": "rgba(212,165,116,0.3)",
      "--border": "#2a2a2a",
    },
    dark: true,
  },
  {
    id: "notebook-tabs",
    name: "Notebook Tabs",
    fonts: "https://fonts.googleapis.com/css2?family=Bodoni+Moda:wght@400;700&family=DM+Sans:wght@400;500&display=swap",
    fontFamily: { display: "'Bodoni Moda', serif", body: "'DM Sans', sans-serif" },
    colors: {
      "--bg-primary": "#2d2d2d",
      "--bg-secondary": "#f8f6f1",
      "--text-primary": "#1a1a1a",
      "--text-secondary": "#555555",
      "--text-dim": "#999999",
      "--accent": "#98d4bb",
      "--accent-glow": "rgba(152,212,187,0.3)",
      "--border": "#e0ddd8",
    },
    dark: false,
  },
  {
    id: "swiss-modern",
    name: "Swiss Modern",
    fonts: "https://fonts.googleapis.com/css2?family=Archivo:wght@800&family=Nunito:wght@400&display=swap",
    fontFamily: { display: "'Archivo', sans-serif", body: "'Nunito', sans-serif" },
    colors: {
      "--bg-primary": "#ffffff",
      "--bg-secondary": "#f5f5f5",
      "--text-primary": "#000000",
      "--text-secondary": "#333333",
      "--text-dim": "#999999",
      "--accent": "#ff3300",
      "--accent-glow": "rgba(255,51,0,0.2)",
      "--border": "#e0e0e0",
    },
    dark: false,
  },
  {
    id: "vintage-editorial",
    name: "Vintage Editorial",
    fonts: "https://fonts.googleapis.com/css2?family=Fraunces:wght@700;900&family=Work+Sans:wght@400;500&display=swap",
    fontFamily: { display: "'Fraunces', serif", body: "'Work Sans', sans-serif" },
    colors: {
      "--bg-primary": "#f5f3ee",
      "--bg-secondary": "#eae7e0",
      "--text-primary": "#1a1a1a",
      "--text-secondary": "#555555",
      "--text-dim": "#999999",
      "--accent": "#e8d4c0",
      "--accent-glow": "rgba(232,212,192,0.5)",
      "--border": "#ddd8d0",
    },
    dark: false,
  },
];
